# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# Adapted from https://github.com/LGUG2Z/komorebi/blob/e240bc770619fa7c1f311b8a376551f2dde8a2d7/.goreleaser.yml
project_name: claveilleur

before:
  hooks:
    - bash -c 'echo "package main; func main() {}" > dummy.go'

builds:
  - id: claveilleur
    binary: claveilleur
    main: dummy.go
    # env:
    #   - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - replace: true
    id: claveilleur
    hooks:
      post:
        - mkdir -p ./dist/claveilleur_darwin_all
        - bash -c 'cp "$(swift build --show-bin-path -c release --arch arm64 --arch x86_64)/claveilleur" ./dist/claveilleur_darwin_all/claveilleur'

archives:
  - format: tar.gz
    # https://goreleaser.com/customization/archive/#packaging-only-the-binaries
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "all" }}universal2
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      # Use zip for windows archives
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
